import { TERRITORY_CONTROLLER_BODY_COST } from '../spawn/bodyBuilder';

const GLOBAL_AUTO_CLAIM_MIN_RCL = (globalThis as { TERRITORY_AUTO_CLAIM_MIN_RCL?: number })
  .TERRITORY_AUTO_CLAIM_MIN_RCL;
const GLOBAL_AUTO_CLAIM_RESERVATION_MIN_TICKS = (globalThis as {
  TERRITORY_AUTO_CLAIM_RESERVATION_MIN_TICKS?: number;
}).TERRITORY_AUTO_CLAIM_RESERVATION_MIN_TICKS;
const GLOBAL_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY = (globalThis as {
  TERRITORY_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY?: number;
}).TERRITORY_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY;

const DEFAULT_AUTO_CLAIM_MIN_RCL = 3;
const DEFAULT_AUTO_CLAIM_RESERVATION_MIN_TICKS = 4_000;
const DEFAULT_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY = 400;

export const TERRITORY_AUTO_CLAIM_MIN_RCL =
  typeof GLOBAL_AUTO_CLAIM_MIN_RCL === 'number' &&
  Number.isFinite(GLOBAL_AUTO_CLAIM_MIN_RCL) &&
  GLOBAL_AUTO_CLAIM_MIN_RCL > 0
    ? Math.floor(GLOBAL_AUTO_CLAIM_MIN_RCL)
    : DEFAULT_AUTO_CLAIM_MIN_RCL;

export const TERRITORY_AUTO_CLAIM_RESERVATION_MIN_TICKS =
  typeof GLOBAL_AUTO_CLAIM_RESERVATION_MIN_TICKS === 'number' &&
  Number.isFinite(GLOBAL_AUTO_CLAIM_RESERVATION_MIN_TICKS) &&
  GLOBAL_AUTO_CLAIM_RESERVATION_MIN_TICKS > 0
    ? Math.floor(GLOBAL_AUTO_CLAIM_RESERVATION_MIN_TICKS)
    : DEFAULT_AUTO_CLAIM_RESERVATION_MIN_TICKS;

export const TERRITORY_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY =
  typeof GLOBAL_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY === 'number' &&
  Number.isFinite(GLOBAL_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY) &&
  GLOBAL_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY >= 0
    ? Math.floor(GLOBAL_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY)
    : DEFAULT_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY;

export const TERRITORY_AUTO_CLAIM_REQUIRED_ENERGY =
  TERRITORY_CONTROLLER_BODY_COST + TERRITORY_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY;

export function isTerritoryAutoClaimReservationMature(ticksToEnd: number | undefined): boolean {
  return (
    typeof ticksToEnd === 'number' &&
    Number.isFinite(ticksToEnd) &&
    ticksToEnd >= TERRITORY_AUTO_CLAIM_RESERVATION_MIN_TICKS
  );
}

export function getTerritoryAutoClaimBodyEnergyBudget(energyAvailable: number): number {
  return Math.max(0, Math.floor(energyAvailable) - TERRITORY_AUTO_CLAIM_BOOTSTRAP_RESERVE_ENERGY);
}
