export const OFFICIAL_SHARD = 'shardX';
export const STRATEGIC_FOCUS_ROOM = 'W3N9';

export const OFFICIAL_ROOM_CANDIDATES = [
  'E17S59',
  'E26S49',
  'E19S57',
  STRATEGIC_FOCUS_ROOM
] as const;

export const STRATEGY_SUPPORTED_SHARDS = [OFFICIAL_SHARD] as const;
export const STRATEGY_SUPPORTED_ROOMS = [STRATEGIC_FOCUS_ROOM] as const;

export const STRATEGIC_ROOM_AUDIT_LITERALS = [
  ...OFFICIAL_ROOM_CANDIDATES,
  'W3N8',
  'W2N9',
  'E17S58',
  'E18S59'
] as const;
