import {
  ACTIVE_OFFICIAL_ROOM_NAMES,
  ACTIVE_OFFICIAL_ROOM_SELECTION,
  ACTIVE_OFFICIAL_SHARDS,
  OFFICIAL_ROOM_CANDIDATES as OFFICIAL_ROOM_SELECTION_CANDIDATES,
  PRODUCTION_ROOM_SELECTION_LITERAL_NAMES
} from './roomSelection';

export const OFFICIAL_SHARD = ACTIVE_OFFICIAL_ROOM_SELECTION.shard;
export const STRATEGIC_FOCUS_ROOM = ACTIVE_OFFICIAL_ROOM_SELECTION.roomName;

export const OFFICIAL_ROOM_CANDIDATES = OFFICIAL_ROOM_SELECTION_CANDIDATES.map(
  (candidate) => candidate.roomName
);

export const STRATEGY_SUPPORTED_SHARDS = [...ACTIVE_OFFICIAL_SHARDS];
export const STRATEGY_SUPPORTED_ROOMS = [...ACTIVE_OFFICIAL_ROOM_NAMES];

export const STRATEGIC_ROOM_AUDIT_LITERALS = [...PRODUCTION_ROOM_SELECTION_LITERAL_NAMES];
