#!/usr/bin/env python3
"""Prepare a secrets-safe private Screeps smoke-test workspace.

The harness intentionally stops short of starting Docker. It writes ignored
runtime files and prints the exact manual continuation commands for the pinned
private-server path that has already passed once.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import textwrap
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RUNTIME_DIR = ROOT / "runtime-artifacts" / "private-server-smoke"
LOCAL_SECRET_ENV = Path("/root") / ".secret" / ".env"
MAP_FILE = "map-0b6758af.json"
MAP_URL = f"https://maps.screepspl.us/maps/{MAP_FILE}"
MAP_CONTAINER_PATH = f"/screeps/maps/{MAP_FILE}"
SERVER_URL = "http://127.0.0.1:21025"
SMOKE_ROOM = "E1S1"
SMOKE_SHARD = "shardX"
SMOKE_SPAWN = "Spawn1"

PINNED_PACKAGES = {
    "ssri": "8.0.1",
    "cacache": "15.3.0",
    "passport-steam": "1.0.17",
    "minipass-fetch": "2.1.2",
    "express-rate-limit": "6.7.0",
    "body-parser": "1.20.3",
    "path-to-regexp": "0.1.12",
    "psl": "1.10.0",
}

MODS = [
    "screepsmod-auth",
    "screepsmod-admin-utils",
    "screepsmod-mongo",
]


@dataclass(frozen=True)
class SecretPresence:
    present: bool
    sources: tuple[str, ...]

    @property
    def summary(self) -> str:
        if not self.present:
            return "missing"
        return "present (" + ", ".join(self.sources) + ")"


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def build_config() -> str:
    pinned = "\n".join(f"  {name}: {version}" for name, version in PINNED_PACKAGES.items())
    mods = "\n".join(f"  - {mod}" for mod in MODS)
    return (
        "# Generated by scripts/screeps-private-smoke-harness.py prepare.\n"
        "# This file is under ignored runtime-artifacts/. Do not commit local secrets.\n"
        "steamKeyFile: STEAM_KEY\n"
        "version: 4.2.21\n"
        "nodeVersion: Erbium\n"
        "pinnedPackages:\n"
        f"{pinned}\n"
        "mods:\n"
        f"{mods}\n"
        "serverConfig:\n"
        "  welcomeText: \"Local Screeps MVP pinned smoke server\"\n"
        "  tickRate: 200\n"
        f"  shardName: {SMOKE_SHARD}\n"
        f"  mapFile: {MAP_CONTAINER_PATH}\n"
    )


def build_compose() -> str:
    return textwrap.dedent(
        """\
        # Generated by scripts/screeps-private-smoke-harness.py prepare.
        # Run Docker Compose manually from this ignored directory when ready.
        version: "3.8"
        services:
          screeps:
            image: screepers/screeps-launcher:latest
            ports:
              - "127.0.0.1:21025:21025"
            volumes:
              - ./:/screeps
            depends_on:
              - mongo
              - redis
          mongo:
            image: mongo:8
            volumes:
              - ./volumes/mongo:/data/db
          redis:
            image: redis:7
            volumes:
              - ./volumes/redis:/data
        """
    )


def is_nonempty_steam_key_file(path: Path) -> bool:
    try:
        return path.is_file() and path.stat().st_size > 0
    except OSError:
        return False


def env_file_mentions_steam_key(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        name, _, value = stripped.partition("=")
        if name.strip() == "STEAM_KEY" and value.strip().strip("'\""):
            return True
    return False


def detect_steam_key(runtime_dir: Path, environ: dict[str, str] | None = None) -> SecretPresence:
    env = os.environ if environ is None else environ
    sources: list[str] = []
    if env.get("STEAM_KEY"):
        sources.append("STEAM_KEY environment variable")

    probes = [
        (runtime_dir / "STEAM_KEY", is_nonempty_steam_key_file),
        (runtime_dir / ".env", env_file_mentions_steam_key),
        (ROOT / ".env", env_file_mentions_steam_key),
        (LOCAL_SECRET_ENV, env_file_mentions_steam_key),
    ]
    for path, probe in probes:
        if probe(path):
            sources.append(rel(path))

    return SecretPresence(bool(sources), tuple(sources))


def build_plan(runtime_dir: Path) -> str:
    runtime_rel = rel(runtime_dir)
    return textwrap.dedent(
        f"""\
        # Pinned private-server smoke next commands

        Run these from the repository root. They do not echo secret values; keep shell tracing disabled.

        ```bash
        cd {runtime_rel}
        if ! test -s STEAM_KEY; then
          printf '%s\\n' 'Create ignored file ./STEAM_KEY with the Steam Web API key before starting Docker.' >&2
          exit 1
        fi
        test -s maps/{MAP_FILE} || python3 - <<'PY'
        import urllib.request
        from pathlib import Path

        url = '{MAP_URL}'
        request = urllib.request.Request(url, headers={{'User-Agent': 'screeps-private-smoke-harness/1.0'}})
        with urllib.request.urlopen(request, timeout=30) as response:
            Path('maps/{MAP_FILE}').write_bytes(response.read())
        PY

        docker compose up -d

        until curl -fsS {SERVER_URL}/api/version >/tmp/screeps-private-smoke-version.json; do
          sleep 2
        done

        docker compose exec -T screeps screeps-launcher cli <<'EOF'
        system.resetAllData()
        utils.importMapFile('{MAP_CONTAINER_PATH}')
        EOF

        docker compose restart screeps

        until curl -fsS {SERVER_URL}/api/version >/tmp/screeps-private-smoke-version.json; do
          sleep 2
        done

        docker compose exec -T screeps screeps-launcher cli <<'EOF'
        system.resumeSimulation()
        EOF
        ```

        Register the local smoke user, authenticate without printing the token, and upload the built bot:

        ```bash
        export SMOKE_URL={SERVER_URL}
        export SMOKE_USER=smoke
        export SMOKE_EMAIL=smoke@example.invalid
        read -rsp 'Private smoke password: ' SMOKE_PASSWORD; printf '\\n'

        python3 - <<'PY'
        import json
        import os
        import urllib.error
        import urllib.request
        from pathlib import Path

        base = os.environ['SMOKE_URL'].rstrip('/')
        user = os.environ['SMOKE_USER']
        email = os.environ['SMOKE_EMAIL']
        password = os.environ['SMOKE_PASSWORD']

        def request_json(path, payload=None, headers=None):
            data = None if payload is None else json.dumps(payload).encode()
            request = urllib.request.Request(
                base + path,
                data=data,
                headers={{'Content-Type': 'application/json', **(headers or {{}})}},
                method='GET' if payload is None else 'POST',
            )
            with urllib.request.urlopen(request, timeout=30) as response:
                body = response.read()
            return json.loads(body.decode() or '{{}}')

        try:
            request_json('/api/register/submit', {{
                'username': user,
                'email': email,
                'password': password,
            }})
        except urllib.error.HTTPError as exc:
            body = exc.read().decode(errors='replace').lower()
            if exc.code not in (400, 409) or 'exist' not in body:
                raise

        auth = request_json('/api/auth/signin', {{'email': email, 'password': password}})
        token = auth.get('token')
        if not isinstance(token, str) or not token:
            raise SystemExit('auth did not return a token')
        Path('.smoke-token').write_text(token + '\\n', encoding='utf-8')
        Path('.smoke-token').chmod(0o600)

        main = Path('../../prod/dist/main.js').read_text(encoding='utf-8')
        request_json('/api/user/code', {{
            'branch': 'default',
            'modules': {{'main': main}},
        }}, headers={{'X-Username': user, 'X-Token': token}})
        print('registered/authenticated/uploaded without printing token')
        PY
        unset SMOKE_PASSWORD
        ```

        Place the first spawn in the imported room:

        ```bash
        python3 - <<'PY'
        import json
        import os
        import urllib.error
        import urllib.request
        from pathlib import Path

        base = os.environ.get('SMOKE_URL', '{SERVER_URL}').rstrip('/')
        user = os.environ.get('SMOKE_USER', 'smoke')
        token = Path('.smoke-token').read_text(encoding='utf-8').strip()
        payload = {{
            'room': '{SMOKE_ROOM}',
            'shard': '{SMOKE_SHARD}',
            'x': 20,
            'y': 20,
            'name': '{SMOKE_SPAWN}',
        }}
        request = urllib.request.Request(
            base + '/api/game/place-spawn',
            data=json.dumps(payload).encode(),
            headers={{'Content-Type': 'application/json', 'X-Username': user, 'X-Token': token}},
            method='POST',
        )
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                response.read()
        except urllib.error.HTTPError as exc:
            body = exc.read().decode(errors='replace').lower()
            if exc.code not in (400, 409) or 'spawn' not in body:
                raise
        print('spawn placement requested')
        PY
        ```

        Collect redacted observations after a few hundred ticks:

        ```bash
        curl -fsS {SERVER_URL}/stats | python3 -m json.tool

        python3 - <<'PY'
        import json
        import os
        import urllib.parse
        import urllib.request
        from pathlib import Path

        base = os.environ.get('SMOKE_URL', '{SERVER_URL}').rstrip('/')
        user = os.environ.get('SMOKE_USER', 'smoke')
        token = Path('.smoke-token').read_text(encoding='utf-8').strip()

        def get(path, params=None):
            url = base + path
            if params:
                url += '?' + urllib.parse.urlencode(params)
            request = urllib.request.Request(url, headers={{'X-Username': user, 'X-Token': token}})
            with urllib.request.urlopen(request, timeout=30) as response:
                return json.load(response)

        def redact(value):
            if isinstance(value, dict):
                redacted = {{}}
                for key, child in value.items():
                    lowered = str(key).lower()
                    if 'token' in lowered or 'password' in lowered or lowered == 'email':
                        redacted[key] = '<redacted>'
                    else:
                        redacted[key] = redact(child)
                return redacted
            if isinstance(value, list):
                return [redact(child) for child in value]
            return value

        observations = {{
            'overview': get('/api/user/overview'),
            'room_overview': get('/api/game/room-overview', {{'room': '{SMOKE_ROOM}', 'shard': '{SMOKE_SHARD}'}}),
            'room_status': get('/api/game/room-status', {{'room': '{SMOKE_ROOM}', 'shard': '{SMOKE_SHARD}'}}),
            'code_roundtrip_main_length': len(get('/api/user/code', {{'branch': 'default'}}).get('modules', {{}}).get('main', '')),
        }}
        print(json.dumps(redact(observations), indent=2, sort_keys=True))
        PY

        docker compose exec -T mongo mongosh screeps --quiet --eval "db['rooms.objects'].find({{room:'{SMOKE_ROOM}', type:{{$in:['spawn','creep','controller']}}}}, {{_id:0, name:1, type:1, x:1, y:1, level:1, 'owner.username':1}}).limit(30).toArray()"
        docker compose logs --no-color --tail=400 screeps | grep -E 'Unhandled|TypeError|ReferenceError|Error:' || true
        ```

        Stop and keep or remove ignored state when done:

        ```bash
        docker compose down --remove-orphans
        # Optional full reset:
        # rm -rf volumes .smoke-token STEAM_KEY
        ```
        """
    )


def build_readme(runtime_dir: Path, secret_presence: SecretPresence, map_cached: bool) -> str:
    map_status = "present" if map_cached else "missing"
    return textwrap.dedent(
        f"""\
        # Private Server Smoke Runtime Workspace

        Generated by `scripts/screeps-private-smoke-harness.py prepare`.

        This directory is ignored by git. It may contain local secrets, downloaded maps,
        Docker volumes, and transient API tokens. Do not copy values from this directory
        into committed documentation.

        ## Current local readiness

        - Steam key: {secret_presence.summary}
        - Map cache `maps/{MAP_FILE}`: {map_status}
        - Docker is not started by this harness.

        ## Secret handling

        The generated `config.yml` uses `steamKeyFile: STEAM_KEY`. Before starting
        Docker, create `./STEAM_KEY` in this ignored directory or adapt the config
        locally. If `/root/.secret/.env` contains `STEAM_KEY`, copy it without shell
        tracing and without printing the value. The file should contain only the Steam
        Web API key. The harness never writes an environment-provided `STEAM_KEY`
        value to disk and never prints it.

        `STEAM_KEY.example` is a placeholder only.

        {build_plan(runtime_dir)}
        """
    )


def write_if_changed(path: Path, content: str) -> bool:
    existing = None
    try:
        existing = path.read_text(encoding="utf-8")
    except OSError:
        pass
    if existing == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def download_map(map_path: Path, timeout: int) -> str:
    request = urllib.request.Request(MAP_URL, headers={"User-Agent": "screeps-private-smoke-harness/1.0"})
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            content = response.read()
    except (OSError, urllib.error.URLError) as exc:
        return f"map download skipped/failed: {type(exc).__name__}"

    if not content.lstrip().startswith(b"{"):
        return "map download skipped/failed: response was not JSON"

    map_path.parent.mkdir(parents=True, exist_ok=True)
    map_path.write_bytes(content)
    return f"downloaded {rel(map_path)}"


def command_prepare(args: argparse.Namespace) -> int:
    runtime_dir = Path(args.runtime_dir).resolve()
    maps_dir = runtime_dir / "maps"
    map_path = maps_dir / MAP_FILE
    runtime_dir.mkdir(parents=True, exist_ok=True)
    maps_dir.mkdir(parents=True, exist_ok=True)
    (runtime_dir / "volumes").mkdir(parents=True, exist_ok=True)

    map_result = "map download not requested"
    if args.download_map and not map_path.exists():
        map_result = download_map(map_path, args.timeout)
    elif args.download_map:
        map_result = f"map already present: {rel(map_path)}"

    secret_presence = detect_steam_key(runtime_dir)
    changed = []
    for path, content in [
        (runtime_dir / "docker-compose.yml", build_compose()),
        (runtime_dir / "config.yml", build_config()),
        (runtime_dir / "STEAM_KEY.example", "REDACTED_STEAM_WEB_API_KEY_GOES_HERE\n"),
        (maps_dir / "README.md", f"Place or download {MAP_FILE} here. Source: {MAP_URL}\n"),
        (runtime_dir / "README.md", build_readme(runtime_dir, secret_presence, map_path.exists())),
    ]:
        if write_if_changed(path, content):
            changed.append(rel(path))

    print(f"prepared {rel(runtime_dir)}")
    print(f"steam key: {secret_presence.summary}")
    print(map_result)
    if changed:
        print("updated:")
        for path in changed:
            print(f"  {path}")
    else:
        print("updated: no file changes")

    if not args.no_plan:
        print()
        print(build_plan(runtime_dir).rstrip())
    return 0


def command_plan(args: argparse.Namespace) -> int:
    print(build_plan(Path(args.runtime_dir).resolve()).rstrip())
    return 0


def assert_contains(haystack: str, needles: Iterable[str]) -> int:
    count = 0
    for needle in needles:
        if needle not in haystack:
            raise AssertionError(f"missing expected text: {needle}")
        count += 1
    return count


def assert_not_contains(haystack: str, needles: Iterable[str]) -> int:
    count = 0
    for needle in needles:
        if needle and needle in haystack:
            raise AssertionError("rendered template leaked a forbidden sentinel")
        count += 1
    return count


def command_self_test(_: argparse.Namespace) -> int:
    checks = 0
    config = build_config()
    compose = build_compose()
    plan = build_plan(DEFAULT_RUNTIME_DIR)
    readme = build_readme(
        DEFAULT_RUNTIME_DIR,
        SecretPresence(True, ("STEAM_KEY environment variable",)),
        map_cached=False,
    )

    checks += assert_contains(
        config,
        [
            "version: 4.2.21",
            "nodeVersion: Erbium",
            f"mapFile: {MAP_CONTAINER_PATH}",
            "steamKeyFile: STEAM_KEY",
        ],
    )
    checks += assert_contains(config, [f"  {name}: {version}" for name, version in PINNED_PACKAGES.items()])
    checks += assert_contains(config, [f"  - {mod}" for mod in MODS])
    checks += assert_contains(
        compose,
        [
            "screepers/screeps-launcher:latest",
            "mongo:8",
            "redis:7",
            '"127.0.0.1:21025:21025"',
            "./:/screeps",
        ],
    )
    checks += assert_contains(
        plan,
        [
            "docker compose up -d",
            f"utils.importMapFile('{MAP_CONTAINER_PATH}')",
            "system.resumeSimulation()",
            "/api/register/submit",
            "/api/user/code",
            "/api/game/place-spawn",
            "/api/user/overview",
            "mongosh screeps",
            "docker compose down --remove-orphans",
        ],
    )

    sentinel = "super-secret-steam-key-sentinel"
    leak_probe = config + compose + plan + readme
    checks += assert_not_contains(leak_probe, [sentinel, "STEAM_KEY=super-secret"])

    detected = detect_steam_key(DEFAULT_RUNTIME_DIR, {"STEAM_KEY": sentinel})
    if not detected.present or "STEAM_KEY environment variable" not in detected.sources:
        raise AssertionError("STEAM_KEY presence detection failed without reading or printing value")
    checks += 1

    temp_env = DEFAULT_RUNTIME_DIR / ".env"
    temp_env.parent.mkdir(parents=True, exist_ok=True)
    existing_temp_env = temp_env.read_bytes() if temp_env.exists() else None
    temp_env.write_text("STEAM_KEY=super-secret\n", encoding="utf-8")
    try:
        detected_file = detect_steam_key(DEFAULT_RUNTIME_DIR, {})
    finally:
        if existing_temp_env is None:
            temp_env.unlink(missing_ok=True)
        else:
            temp_env.write_bytes(existing_temp_env)
    if not detected_file.present or rel(temp_env) not in detected_file.sources:
        raise AssertionError("STEAM_KEY .env presence detection failed")
    checks += 1

    safe_fragment = re.sub(r"[^A-Za-z0-9_.-]+", "-", rel(DEFAULT_RUNTIME_DIR))
    if not safe_fragment:
        raise AssertionError("runtime directory relative path sanity check failed")
    checks += 1

    print(f"self-test passed ({checks} checks)")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--runtime-dir",
        default=str(DEFAULT_RUNTIME_DIR),
        help="ignored runtime workspace to prepare or describe",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    self_test = subparsers.add_parser("self-test", help="run offline harness checks")
    self_test.set_defaults(func=command_self_test)

    prepare = subparsers.add_parser("prepare", help="write ignored runtime files and print next steps")
    prepare.add_argument("--download-map", action="store_true", help="try to cache the pinned map JSON")
    prepare.add_argument("--timeout", type=int, default=30, help="map download timeout in seconds")
    prepare.add_argument("--no-plan", action="store_true", help="do not print the next-step command plan")
    prepare.set_defaults(func=command_prepare)

    plan = subparsers.add_parser("plan", help="print the manual next-step commands")
    plan.set_defaults(func=command_plan)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except BrokenPipeError:
        return 1
    except Exception as exc:  # noqa: BLE001 - keep CLI errors concise and secret-free
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
