apiVersion: 1

datasources:
  - name: Screeps RL Metrics SQLite
    uid: screeps-rl-metrics-sqlite
    type: frser-sqlite-datasource
    access: proxy
    orgId: 1
    isDefault: true
    editable: false
    jsonData:
      path: /var/lib/grafana/rl-metrics/rl_metrics.sqlite
